---
ID: "fd32c5e6-9f19-4ef5-b38a-48ec1e197402"
Parent: "087e1ea5-6280-4575-9e70-85b588db91b2"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/system/Settings/Project
DB: master
SharedFields:
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking>
      <profile
        id="{00979BCE-14A9-4E1C-AA93-969982D2B65A}"
        name="Site Interest"
        presets="mark|100||">
        <key
          name="Business"
          value="5" />
        <key
          name="Products"
          value="2" />
        <key
          name="Supplies"
          value="1" />
        <key
          name="Support"
          value="1" />
      </profile>
    </tracking>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Value: "20180917T125444:636727856849203853Z"
