---
ID: "c82dc5ff-09ef-4403-96d3-3caf377b8c5b"
Parent: "df639de8-c9e7-4b18-967e-b1a14a8ff221"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Foundation/Multisite/Datasource Configuration
DB: master
SharedFields:
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking>
      <profile
        id="{00979BCE-14A9-4E1C-AA93-969982D2B65A}"
        name="Site Interest"
        presets="mark|100||">
        <key
          name="Business"
          value="5" />
        <key
          name="Products"
          value="2" />
        <key
          name="Supplies"
          value="1" />
        <key
          name="Support"
          value="1" />
      </profile>
    </tracking>
Languages:
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Value: "20180917T125156:636727855165503465Z"
