---
ID: "fb9a9d95-ec81-4ada-85ba-00be5de0fba9"
Parent: "04c34cf5-b7ea-4408-88e8-5fc851173dbd"
Template: "04c34cf5-b7ea-4408-88e8-5fc851173dbd"
Path: /sitecore/templates/Feature/Maps/Map Type/__Standard Values
DB: master
SharedFields:
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking>
      <profile
        id="{00979BCE-14A9-4E1C-AA93-969982D2B65A}"
        name="Site Interest"
        presets="mark|100||">
        <key
          name="Business"
          value="5" />
        <key
          name="Products"
          value="2" />
        <key
          name="Supplies"
          value="1" />
        <key
          name="Support"
          value="1" />
      </profile>
    </tracking>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151214T093145Z
    - ID: "4a724065-e4ca-4cdd-9027-f56ceef1b082"
      Hint: Name
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
